### ISSUE TITLE
Authentication issue to push images to GCP

### ISSUE THREAD

**Issue by clakech** [CircleCI-Public/gcp-cli-orb#12]
### Orb version
1.8.2

### What happened

when pushing to GCR on GCP when have this issue:

docker push eu.gcr.io/$GOOGLE_PROJECT_ID/path/to/pr/module:$sha1

```
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

current workaround is:
```
echo $GCLOUD_SERVICE_KEY > ${HOME}/gcp-key.json
            set -x
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud auth configure-docker --quiet --project $GOOGLE_PROJECT_ID
            gcloud info
```

**Comment by iynere** [comment]
awesome, wanna open a PR to add those commands ? @clakech 

thank you !

**Comment by clakech** [comment]
yes I could but I am not an expert here but this workaround works fine.

do anyone else have this issue too ?

just to confirm before PR this

**Comment by iynere** [comment]
sure, we can wait & see if anyone else has run into it. we haven't seen this issue internally w/ any of our orbs that depend on this orb, but it's possible we're not testing for this edge case.

**Comment by lokst** [comment]
Marking this as resolved as the `circleci/gcp-gcr` orb has a `gcr-auth` command that can help with this: https://circleci.com/orbs/registry/orb/circleci/gcp-gcr#commands-gcr-auth
