### ISSUE TITLE
gcloud command not found after upgrading to 1.8.4 from 1.3.0

### ISSUE THREAD

**Issue by JasonTheAdams** [CircleCI-Public/gcp-cli-orb#19]
### Orb version

Upgraded from 1.3.0 to 1.8.4

### What happened

I'm having an issue with deployment so I SSH'ed into the job to figure out what's going on. I immediately found that the `gcloud` command no longer is available on the CLI. If I type `gcloud --version` I get a "command not found" error.

I did find, however, that there is a `google-cloud-sdk` directory in the root, which contains the executable. So I can run the command via `./google-cloud-sdk/bin/gcloud`. But this is tedious.

### Expected behavior

Ideally, it would work as it did before. I suppose all that really needs to happen is for the new `gcloud` location to be added to the `$PATH`. However it's done, it's important to be able to SSH into the job and troubleshoot using the initialized `gcloud` command.

**Comment by bryanhuntesl** [comment]
I spoke to support and they directed me here, I'm having a similar issue - perhaps because I'm running the orb on a docker image which is alpine, and as a result the shell is 'sh' (busybox) as opposed to bash approximation of this behavior. 

```
#!/bin/sh -eo pipefail
install () {
  # Set sudo to work whether logged in as root user or non-root user
  if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
  cd ~/
  curl -s https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-283.0.0-linux-x86_64.tar.gz | tar xz
  echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
}

if grep 'docker\|lxc' /proc/1/cgroup > /dev/null 2>&1; then
  if [[ $(command -v gcloud) == "" ]]; then
    install
  else
    echo "gcloud CLI is already installed."
  fi
else
  echo "----------------------------------------------------------------------------------------------------"
  echo "this is a machine executor job, replacing default installation of gcloud CLI"
  echo "----------------------------------------------------------------------------------------------------"
  sudo rm -rf /opt/google-cloud-sdk
  install
fi
sh: : unknown operand
gcloud CLI is already installed.
CircleCI received exit code 0
```

````
#!/bin/sh -eo pipefail
gcloud version
/bin/sh: gcloud: not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by JasonTheAdams** [comment]
In the meantime, I just started running this at when I first connect, then it works as expected:
```bash
export PATH="/usr/home/google-cloud-sdk/bin:$PATH"
```

**Comment by kawerewagaba** [comment]
Similar situation: trying to deploy a function using `gcloud` - with `node-alpine` as my primary container, and the `circleci/gcp-cli@2.2.0` orb to install and initialize `gcloud`. 

<img width="1169" alt="Screenshot 2021-09-27 at 12 41 38" src="https://user-images.githubusercontent.com/24539185/134884913-34c6f102-5447-4352-b018-7f7b6c662437.png">

I ssh-ed into the job but could find the `google-cloud-sdk` under `/usr/home`. I tried `which gcloud` but that returned empty, confirming that possibly the utility wasn't installed - which I find confusing, as `"gcloud CLI is already installed"`.
<img width="223" alt="Screenshot 2021-09-27 at 12 44 43" src="https://user-images.githubusercontent.com/24539185/134885591-d8a2124a-e886-449e-88e1-1870fd38676a.png">

Anyone with more context on what could be going on?

**Comment by koconnor-ampion** [comment]
@Jaryt and @KyleTryon ,  I believe that a portion of @kawerewagaba 's problem could be fixed quite easily.  It is related to @bryanhuntesl 's report.  The busybox in an alpine distribution treats the test slightly differently than standard 'bourne' when it comes to empty values in variables.  Changing:
`  if [[ $(command -v gcloud) == "" ]]; then`
to
`  if [[ "$(command -v gcloud)" == "" ]]; then`
should fix the issue and not bother a standard bourne shell either.

Perhaps @JasonTheAdams problem is related in that the BASH_ENV is handled differently, and the PATH does not end up being set in the current invocation, so the follow-on step where the cli is not found is because the PATH does not include the  `/root/google-cloud-sdk/bin:`. (assuming root is correct which it would be for me.

-kevin

**Comment by KengoTODA** [comment]
I found that the following part `  if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi` has the similar problem: We need to wrap `$EUID` with double-quotes.

**Comment by tcaddy** [comment]
> In the meantime, I just started running this at when I first connect, then it works as expected:
> 
> ```shell
> export PATH="/usr/home/google-cloud-sdk/bin:$PATH"
> ```

This one just helped me find the `gcloud` binary at CircleCI that gets installed from this Orb: https://circleci.com/developer/orbs/orb/circleci/gcp-cli
