### ISSUE TITLE
install: Fails on Alpine

### ISSUE THREAD

**Issue by whyman** [CircleCI-Public/gcp-cli-orb#21]
### Orb version

1.8.5

### What happened
```#!/bin/sh -eo pipefail
install () {
  # Set sudo to work whether logged in as root user or non-root user
  if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
  cd ~/
  curl -Ss --retry 5 https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-283.0.0-linux-x86_64.tar.gz | tar xz
  echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
}

if grep 'docker\|lxc' /proc/1/cgroup > /dev/null 2>&1; then
  if [[ $(command -v gcloud) == "" ]]; then
    install
  else
    echo "gcloud CLI is already installed."
  fi
else
  echo "----------------------------------------------------------------------------------------------------"
  echo "this is a machine executor job, replacing default installation of gcloud CLI"
  echo "----------------------------------------------------------------------------------------------------"
  sudo rm -rf /opt/google-cloud-sdk
  install
fi

sh: : unknown operand
gcloud CLI is already installed.

CircleCI received exit code 0
```

### Expected behavior
It should work on alpines default shell (busybox). If the script requires bash it should set that in the hashbang.

**Comment by dsayling** [comment]
The install command is not supported on alpine currently. However, you could get this running on a modified alpine image.

First, in circleci's run step, the declaration contains a `shell` key, where the shell can be set. If not set, a default shell is used: https://circleci.com/docs/2.0/configuration-reference/#default-shell-options
As you can see, `/bin/bash` is the default shell of choice, however if not present, `/bin/sh` is used. If you are using some variant of a default alpine image, bash is not installed. I believe this is core issue you are seeing. 

Next, for the script, you also need curl, which is not in the default image. Once gcloud sdk is downloaded, the `gcloud` command depends on an installation of python at runtime - which is not included in alpine as well. You can install them with apk.  
```
apk add bash curl python3-dev
```

Hope this helps while we evaluate full alpine support.

**Comment by KyleTryon** [comment]
Closing with above comment
