### ISSUE TITLE
Cannot use gcloud config initialized by the "initialize" orb command because config is root

### ISSUE THREAD

**Issue by looztra** [CircleCI-Public/gcp-cli-orb#3]
All the commands executed by the `initialize` orb command are run either by root or with sudo, hence, the gcloud auth commands (executed by the initialize orb command) generate a valid gcloud config for the **root** user, **not** for the user running in a container when a job relies on a docker container executor and not a "machine" executor.

Question : why did you choose to use `sudo` when user is not root? (that is the cas when the job is running inside a container)

Note : this issue is a follow up of this Twitter thread : https://twitter.com/drazisil/status/1097909301857927168?s=17

**Comment by clakech** [comment]
a workaround proposal from twitter is to copy the config from root dir to the current user dir

**Comment by iynere** [comment]
thank you, i think i've been running into this issue myself but wasn't sure what was going on... working on an orb that makes heavy use of this one, so i'll make sure to resolve this as i work on it.
