### ISSUE TITLE
New error in orb: gcloud crashed (ValueError): invalid width 0 (must be > 0) when tagging images

### ISSUE THREAD

**Issue by joe-hilling** [CircleCI-Public/gcp-cli-orb#36]
### Orb version

circleci/gcp-cli@1.3.0

### What happened

The following step fails.
```
IMAGE_TO_TAG="eu.gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}"
echo Tagging "${IMAGE_TO_TAG}"
gcloud container images add-tag "${IMAGE_TO_TAG}" \
             eu.gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:latest
```
Echo shows our project
```
Tagging eu.gcr.io/CHANGED_PROJECT_NAME/data-server:VALID_TAG
ERROR: gcloud crashed (ValueError): invalid width 0 (must be > 0)
```
Where the project name is valid / exists and the VALID_TAG is visible in the google cloud container registry.

I have tried to run this code from my personal machine and the statement executes without issue.

This workflow has run hundreds of times previously without fail and the most recent commit that triggered it had no changes to the circleci config. The container build and test steps pass without error.

### Expected behavior

Image is successfully tagged with `latest`

**Comment by joe-hilling** [comment]
Same issue with `circleci/gcp-cli@2.2.0`

**Comment by EricRibeiro** [comment]
Seems like this issue was related to the cloud-sdk version and it's fixed.
