### ISSUE TITLE
region / zone should not be required

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/gcp-cli-orb#38]
### Orb version
`circleci/gcp-cli@2.2.0` (current)

### What happened
https://circleci.com/developer/orbs/orb/circleci/gcp-cli#commands-initialize
lists all the env vars as not required. They are technically optional, since they have defaults, but the job will fail if the env vars themselves are not set.

### Expected behavior
* I should not have to provide a region or zone to use this command (the module should not fail, but simply not set those values)
* The docs should make it clear that the variables are the env var holding the value, vs. the place you set the value itself (admittedly, the variable type is `env_var_name`).

**Comment by wyardley** [comment]
@BytesGuy @gmemstr would one of you be able to take a look at the associated PR, as well as the other open PRs in this project?

**Comment by gmemstr** [comment]
The `required` field is determined by the presence of a default value for the parameter. We should have some validation for this within the orb though. I'll take a look.
