### ISSUE TITLE
Feature request: Use OIDC and Workload Identity Federation for increased security

### ISSUE THREAD

**Issue by novedevo** [CircleCI-Public/gcp-cli-orb#41]
CircleCI recently began supporting OIDC, similarly to GitHub Actions and other CI providers (https://circleci.com/docs/2.0/openid-connect-tokens/). The current GCP orbs use service account keys, whereas the [GCP GitHub Actions](https://github.com/google-github-actions/auth) use OIDC as best practices indicate. I'm not comfortable recommending these orbs to the rest of my team until they use OIDC instead of requiring service account private key management. Thank you!

**Comment by Jaryt** [comment]
Merged in #56
