### ISSUE TITLE
error gcloud: command not found

### ISSUE THREAD

**Issue by SamuelTissot** [CircleCI-Public/gcp-cli-orb#5]
### Orb version

v1.0.1

### What happened

when I run the steps 

```yaml
steps:
  - gcp-cli/install
  - gcp-cli/initialize
```

I get the error: `error gcloud: command not found`
#### step: Install
the install step seems to have completed without any issue

#### step: initialize
I get the error: `error gcloud: command not found`

output:
```bash
#!/bin/bash -eo pipefail
# Set sudo to work whether logged in as root user or non-root user
if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

# Store service account
echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

# Initialize gcloud CLI
$SUDO gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
$SUDO gcloud --quiet config set project $GCLOUD_PROJECT_ID
$SUDO gcloud --quiet config set compute/zone $GCLOUD_PROJECT_REGION
sudo: gcloud: command not found
Exited with code 1
```

### Expected behavior

```bash
Activated service account credentials for: [ ---CREDENTIAL--- ]
Updated property [core/project].
Updated property [compute/zone].
```

Notes:
----

In my account the error started today Feb 26th 2019

**Comment by SamuelTissot** [comment]
After running it once more I do get an error on the `initialize` step

`E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)`

**Comment by SamuelTissot** [comment]
```
if [[ $(command -v lsb_release) == "" ]]; then
  $SUDO apt-get update && $SUDO apt-get -y install lsb-release
  export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
else
  export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
fi
```

`$(command -v lsb_release)` returns `No LSB modules are available` so `lsb-release` never gets install

**Comment by SamuelTissot** [comment]
fix the issue 
debian packages where not updating correctly I had to had

`apt-get update || apt-get update` prior to running the orbs steps.

**Comment by postalservice14** [comment]
> fix the issue
> debian packages where not updating correctly I had to had
> 
> `apt-get update || apt-get update` prior to running the orbs steps.

Can someone explain why this works?
