### ISSUE TITLE
gcloud component install waiting for user input

### ISSUE THREAD

**Issue by prakash-fb** [CircleCI-Public/gcp-cli-orb#65]
### Orb version
3.0.1

### What happened
When installing the gcloud component it expects the user to input.

### Expected behavior
orbs should install the component without any issues.

![image](https://user-images.githubusercontent.com/86976390/213445540-17e17012-2498-421d-8866-ccc2cf9dc249.png)

Any change updating kubectl in cimg:gcp image? It use 1.25 version.

**Comment by villesau** [comment]
Same here.

**Comment by villesau** [comment]
Got worked this around. What `components`  is, it essentially just passes what ever it receives to gcloud command, so following fixes the issue:

```
      - gcp-cli/setup:
          components: 'gke-gcloud-auth-plugin kubectl --quiet'
```

I'm having a bit difficult time to understand why this kind of abstraction is even needed. Why not installing and using gcloud directly? The orb seems to just add an extra layer of complexity and extra layer of extra issues.

**Comment by leozhantw** [comment]
Same here.

I'm curious about why don't we just add the `--quiet` [here](https://github.com/CircleCI-Public/gcp-cli-orb/blob/637a5b8c001b577f10b251c5794541c8159cbb88/src/scripts/install.sh#L162)? 🤔 

e.g.
```sh
gcloud --quiet components install "$@"
```

Is there some reason we can't do it there?

**Comment by david-montano-circleci** [comment]
Hello. I will close this given that the `--quiet` was added in the latest versions of this orb.
[See](https://github.com/CircleCI-Public/gcp-cli-orb/blob/v3.2.2/src/scripts/install.sh#L190).
