### ISSUE TITLE
`gcp-cli/setup` command won't pass with gcloud latest version (429.0.0)

### ISSUE THREAD

**Issue by joaomlopes** [CircleCI-Public/gcp-cli-orb#74]
### Orb version

3.0.1

### What happened

Installing the latest gcloud version (429.0.0) will break on the `gcp-cli/setup` command while running the step 
_Initialize gcloud CLI to connect to Google Cloud_ with the error
```
ERROR: gcloud crashed (AttributeError): 'bool' object has no attribute 'lower'
```
Knowing that we can set the version, however this is part of the `gcp-gke/publish-and-rollout-image`  job on the gcp-gke orb.

### Expected behavior

The setup should pass successfully regardless the version.

**Comment by EricRibeiro** [comment]
Thanks for bringing this to our attention. 

This is likely a problem with this version of the CLI or your executor. It should not be related to the orb itself. If you think otherwise, I'll be sure to look into it if you provide more information.
