### ISSUE TITLE
Failed to install gcloud on latest ubuntu machine executor

### ISSUE THREAD

**Issue by yz89122** [CircleCI-Public/gcp-cli-orb#82]
### Orb version

`circleci/gcp-cli@3.1.0`

machine image: `ubuntu-2204:2024.03.1`(from `ubuntu-2204:edge`) and `ubuntu-2004:2024.03.1`(from: `ubuntu-2004:edge`)

### What happened

Installation failed.

error message:

```
The version installed (470.0.0) matches the version requested (470.0.0).
Skipping installation.

ERROR: (gcloud.components.install) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/opt/google/google-cloud-sdk].

Re-run the command with sudo: sudo /opt/google/google-cloud-sdk/bin/gcloud ...

Exited with code exit status 1
```

We were trying to install a gcloud plugin (`gcloud component install ...`).

Currently we use this orb with workaround `sudo chown circleci:circleci -R /opt/google`.

### Expected behavior

Installation succeeded.

**Comment by michaelrode** [comment]
I am having the same issue

**Comment by david-montano-circleci** [comment]
Hello @michaelrode . Thank you for reporting this issue.
I have been trying to reproduce with the latest version of this orb v3.3.0 and it seems it is not happening anymore.
I am attaching some screenshots of the tests I ran.
Please report back if you are still having issues with the latest version of this orb.
Thank you!
<img width="1109" alt="Screenshot 2024-11-18 at 11 03 05 AM" src="https://github.com/user-attachments/assets/6731f651-74e4-4eac-becc-cc87724063da">
<img width="1079" alt="Screenshot 2024-11-18 at 11 03 20 AM" src="https://github.com/user-attachments/assets/12548882-f365-416a-96dc-98680e976e44">
